services:
  - type: web
    name: creditcoach
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 1 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: WATSONX_API_KEY
        sync: false
      - key: WATSONX_PROJECT_ID
        sync: false
      - key: WATSONX_URL
        value: https://us-south.ml.cloud.ibm.com
      - key: WATSONX_MODEL_ID
        value: ibm/granite-4-h-small
